# -*- coding: utf-8 -*-
"""EXAMEN SERIES DE TIEMPO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18dUdmAfgQ2pnS5IRQrwTWVGqUeJr1p_T
"""

import pandas as pd
import numpy as np
from google.colab import files
import statsmodels.api as sm
from statsmodels.tsa.stattools import adfuller, kpss, acf, pacf
from statsmodels.tsa.arima.model import ARIMA
import matplotlib.pyplot as plt

# Upload Excel file for Money Supply
print("Please upload Money Supply Excel file")
ms_upload = files.upload()
ms_filename = list(ms_upload.keys())[0]
ms_df = pd.read_excel(ms_filename)

# Print available columns
print("\nMoney Supply DataFrame columns:", list(ms_df.columns))

# Ask user for the correct column name
value_column = input("Please enter the column name containing Money Supply values: ")

# Extract and clean Money Supply values
try:
    ms_values = ms_df[value_column]
    # Convert to numeric, coercing errors to NaN
    ms_values = pd.to_numeric(ms_values, errors='coerce')
    # Check for non-numeric values
    if ms_values.isna().any():
        print(f"Warning: Money Supply {value_column} contains {ms_values.isna().sum()} non-numeric or missing values")
    # Drop NaN values
    ms_values = ms_values.dropna()
except KeyError:
    print(f"Error: Column '{value_column}' not found in DataFrame")
    print("Please check the column name and try again")
    raise

# Function for unit root tests with interpretation and table
def unit_root_tests(series, name):
    print(f"\nUnit Root Tests for {name}:")

    # ADF Test
    adf_result = adfuller(series)
    print("ADF Test:")
    print(f'ADF Statistic: {adf_result[0]:.4f}')
    print(f'p-value: {adf_result[1]:.4f}')
    print(f'Critical Values: {adf_result[4]}')
    print("Interpretation:")
    adf_conclusion = "Stationary" if adf_result[1] < 0.05 else "Non-stationary"
    if adf_result[1] < 0.05:
        print(f"  - p-value < 0.05: Reject null hypothesis - {name} is stationary")
    else:
        print(f"  - p-value >= 0.05: Fail to reject null - {name} may be non-stationary")

    # KPSS Test
    kpss_result = kpss(series)
    print("\nKPSS Test:")
    print(f'KPSS Statistic: {kpss_result[0]:.4f}')
    print(f'p-value: {kpss_result[1]:.4f}')
    print(f'Critical Values: {kpss_result[3]}')
    print("Interpretation:")
    kpss_conclusion = "Stationary" if kpss_result[1] >= 0.05 else "Non-stationary"
    if kpss_result[1] < 0.05:
        print(f"  - p-value < 0.05: Reject null hypothesis - {name} is non-stationary")
    else:
        print(f"  - p-value >= 0.05: Fail to reject null - {name} may be stationary")

    # Summary table
    summary_table = pd.DataFrame({
        'Test': ['ADF', 'KPSS'],
        'Statistic': [adf_result[0], kpss_result[0]],
        'p-value': [adf_result[1], kpss_result[1]],
        'Conclusion': [adf_conclusion, kpss_conclusion]
    })
    print(f"\n{name} Stationarity Summary:")
    print(summary_table)

    return adf_result, kpss_result

# Perform unit root tests
ms_adf, ms_kpss = unit_root_tests(ms_values, "Money Supply")

# Function for correlogram (ACF and PACF)
def correlogram(series, name, lags=10):
    acf_values = acf(series, nlags=lags, fft=False)
    pacf_values = pacf(series, nlags=lags)

    # Create table
    corr_table = pd.DataFrame({
        'Lag': range(1, lags + 1),
        'ACF': acf_values[1:lags + 1],
        'PACF': pacf_values[1:lags + 1]
    })
    print(f"\nCorrelogram for {name} (first {lags} lags):")
    print(corr_table)

    # Plot ACF and PACF
    plt.figure(figsize=(12, 6))
    plt.subplot(121)
    plt.stem(range(1, lags + 1), acf_values[1:lags + 1])
    plt.title(f'{name} ACF')
    plt.xlabel('Lag')
    plt.ylabel('Autocorrelation')

    plt.subplot(122)
    plt.stem(range(1, lags + 1), pacf_values[1:lags + 1])
    plt.title(f'{name} PACF')
    plt.xlabel('Lag')
    plt.ylabel('Partial Autocorrelation')
    plt.tight_layout()
    plt.show()

# Perform correlogram analysis
correlogram(ms_values, "Money Supply")

# Function to find best ARIMA model with interpretation
def find_best_arima(series, name, max_p=3, max_d=2, max_q=3):
    best_aic = float('inf')
    best_order = None

    for p in range(max_p + 1):
        for d in range(max_d + 1):
            for q in range(max_q + 1):
                try:
                    model = ARIMA(series, order=(p, d, q))
                    results = model.fit()
                    if results.aic < best_aic:
                        best_aic = results.aic
                        best_order = (p, d, q)
                except:
                    continue

    print(f"\nBest ARIMA model for {name}:")
    print(f"Order: {best_order}")
    print(f"AIC: {best_aic:.2f}")
    print("Interpretation:")
    print(f"  - p={best_order[0]}: {best_order[0]} autoregressive term(s)")
    print(f"  - d={best_order[1]}: {best_order[1]} difference(s) needed for stationarity")
    print(f"  - q={best_order[2]}: {best_order[2]} moving average term(s)")
    return best_order

# Find and fit best ARIMA model
ms_order = find_best_arima(ms_values, "Money Supply")
ms_model = ARIMA(ms_values, order=ms_order).fit()

# Forecast next 30 periods
forecast_steps = 30
ms_forecast = ms_model.forecast(steps=forecast_steps)

# Create forecast index
last_index = len(ms_values) - 1
forecast_index = range(last_index + 1, last_index + 1 + forecast_steps)

# Plot original series
plt.figure(figsize=(12, 6))
plt.plot(ms_values, label='Money Supply')
plt.title('Money Supply Values')
plt.legend()
plt.show()

# Plot differenced series
ms_diff = ms_values.diff().dropna()
plt.figure(figsize=(12, 6))
plt.plot(ms_diff, label='Money Supply Diff')
plt.title('Differenced Money Supply Series')
plt.legend()
plt.show()

# Plot original series with forecasts (log scale)
plt.figure(figsize=(12, 6))
plt.plot(ms_values, label='Money Supply Historical')
plt.plot(forecast_index, ms_forecast, label='Money Supply Forecast', color='red')
plt.yscale('log')  # Set y-axis to logarithmic (base 10) scale
plt.title('Money Supply Values with Forecasts (Log Scale)')
plt.legend()
plt.show()

# Detailed forecast plot with confidence intervals and interpretation
def plot_forecast(model, series, name, steps=30):
    forecast_obj = model.get_forecast(steps=steps)
    forecast = forecast_obj.predicted_mean
    conf_int = forecast_obj.conf_int()

    forecast_index = range(len(series), len(series) + steps)

    plt.figure(figsize=(12, 6))
    plt.plot(series, label=f'{name} Historical')
    plt.plot(forecast_index, forecast, label='Forecast', color='red')
    plt.fill_between(forecast_index,
                     conf_int.iloc[:, 0],
                     conf_int.iloc[:, 1],
                     color='pink',
                     alpha=0.3,
                     label='95% Confidence Interval')
    plt.title(f'{name} Forecast')
    plt.legend()
    plt.show()

    # Forecast interpretation
    last_value = series.iloc[-1]
    mean_forecast = forecast.mean()
    print(f"\nForecast Interpretation for {name}:")
    print(f"Last observed value: {last_value:.2f}")
    print(f"Average forecast value: {mean_forecast:.2f}")
    print(f"Forecast change: {mean_forecast - last_value:.2f}")
    if mean_forecast > last_value:
        print("Trend: Upward forecast trend")
    elif mean_forecast < last_value:
        print("Trend: Downward forecast trend")
    else:
        print("Trend: Flat forecast trend")
    print(f"95% CI range at period {steps}: [{conf_int.iloc[-1, 0]:.2f}, {conf_int.iloc[-1, 1]:.2f}]")

# Generate detailed forecast plot and interpretation
plot_forecast(ms_model, ms_values, "Money Supply")

# Print forecast values
print("\nMoney Supply Forecast Values (next 5 periods):")
print(ms_forecast[:5])